version: 1
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "weekly"
